%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 436.0
Camera.fy: 436.0
Camera.cx: 342.350828269073
Camera.cy: 243.7716655954758

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 752
Camera.height: 480

# Camera frames per second
Camera.fps: 20.0

# stereo baseline times fx
Camera.bf: 59.157134

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 480
LEFT.width: 752
LEFT.D: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-0.3776854872703552, 0.12956754863262177, -0.0012180526973679662, -0.0014810010325163603,
    0.0]
LEFT.K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [544.312744140625, 0.0, 368.8247375488281, 0.0, 544.231689453125, 244.36790466308594,
    0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0.999367283504525, -0.005788702590468917, 0.03509307030035351, 0.005817187215085128,
    0.9999828282255596, -0.000709638580779682, -0.03508835980337505, 0.0009133325406330973,
    0.9993837965616509]
LEFT.P:  !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [436.0, 0.0, 342.350828269073, -0.0, 0.0, 436.0, 243.7716655954758, 0.0, 0.0,
    0.0, 1.0, 0.0]

RIGHT.height: 480
RIGHT.width: 752
RIGHT.D: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-0.3743584454059601, 0.12685652077198029, -0.000883784145116806, -0.0011659004958346486,
    0.0]
RIGHT.K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [546.1130981445312, 0.0, 377.9064636230469, 0.0, 546.0208740234375, 244.46920776367188,
    0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0.9994984686584799, 4.21421857555191e-05, 0.031667165540822814, -6.784690835642662e-05,
    0.999999669128763, 0.0008106412037568113, -0.0316671209008764, -0.0008123831610647557,
    0.9994981408124024]
RIGHT.P:  !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [436.0, 0.0, 342.350828269073, 13.568157754838467, 0.0, 436.0, 243.7716655954758,
    0.0, 0.0, 0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
